---
- hosts:                 demo
  tasks:
  - name:               Change hostname
    hostname:
      name:             demo.hyski.pl
  - name:               Innstall htop
    apt:
      update_cache:     yes
      cache_valid_time: 3600
      name:             htop
      state:            latest
