---
all:
  hosts:
    demo:
      # ansible_host:                178.216.200.119
      ansible_python_interpreter:  /usr/bin/python3
      ansible_user:                e24
  children:
    webserwers:
      hosts:
        demo:
    docker:
      hosts:
        demo:
